@startuml

skinparam dpi 600
scale 1200*1800

skinparam roundCorner 6
skinparam shadowing false
skinparam interface {
  backgroundColor WhiteSmoke
}
skinparam actor {
  FontName Open Sans Condensed Light
  FontSize 14
}
skinparam arrow {
  FontName Open Sans Condensed Light
  FontSize 15
}
skinparam note {
  FontName Open Sans Condensed Light
  FontSize 13
  BorderColor #bbb
}
skinparam footer {
  FontName Open Sans Condensed Light
  FontSize 14
  FontColor DimGrey
}
skinparam sequence {
  actorBorderThickness 1.6
  participantBorderThickness 1.2
  LifeLineBorderColor #ccc
  ParticipantFontName Avenir Next Condensed
  DividerBorderColor #eee
  DividerBackgroundColor #fff
  DividerFontName Open Sans Condensed Light
  DividerFontSize 15
  DividerFontStyle Light
  TitleFontName Open Sans Condensed Light
  TitleFontStyle Light
  TitleFontSize 17
}

actor "User" as user #fff
participant "sKYC Main Web UI" as ui
participant "sKYC Main REST API" as api
database "CouchDB" as couch #fff
database "Oracle DB" as oracle #fff

title
SmartKYC > Processing Flow: Call to Audit Api
<font color="DimGrey" size="12">(v. 2018-11-30)</font>
endtitle

== <b>Retrieve audit trail (slow response)</b> ==

user -> ui: submit an edit request
ui -> api: calls /audit/... api
activate api #BBBBFF
couch <->  api: retrieve database data (optional)
oracle <->  api: retrieve database data (optional)
api --> ui: api call ACK
deactivate api
ui --> user: update the view

|||

footer

endfooter

@endumlwho